# Site settings
author: Josh Mulloy
title: A Journey Into Coding
header-img: img/home-bg.png
email: joshmulloy1@gmail.com
copyright_name: Josh Mulloy
description: > # this means to ignore newlines until "baseurl:"
  A Blog about Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jmulloy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
